### ISSUE TITLE
Location Manager didDetermineState not always called.

### ISSUE THREAD

**Issue by desmondmc** [desmondmcnamee/Roomease#17]
It seems that the callback:

```
- (void)locationManager:(CLLocationManager *)manager
      didDetermineState:(CLRegionState)state forRegion:(CLRegion *)region
```

Is not always called when we request the state for the current region:

```
[self.locationManager requestStateForRegion:region];
```

Seems to only work 40-60% of the time when the app is coming to the foreground but works better when the app is already in the foreground and "Refresh Roommates" is pressed (90%).

Thought it might be that ARC is cleaning up the location manager but with some quick investigation that doesn't seem to be the case. Not sure why this is happening.

**Comment by vandita5** [comment]
@desmondmcnamee  5th link https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=didDetermineState+not+called
